// config/assets.js — ÚNICA fuente de rutas de imágenes. Cambia aquí y ejecuta `node scripts/sync-assets.mjs`
// (o simplemente recarga: main.js hidrata los <img data-asset="..."> en el navegador).
// Rutas relativas a la raíz del sitio (funcionan bajo https://USUARIO.github.io/REPO/).
export const assets = {
  logo: "./assets/images/domm-logo.svg",
  og: "./assets/images/og-image.jpg",
  placeholder: "./assets/images/placeholder.svg",
  flame: "./assets/images/flame.svg",
  sello: "./assets/images/sello-people-first.png",
  hero: {
    bg: "./assets/images/hero-bg.svg",
    wordmark: "./assets/images/hero-wordmark.svg",
  },
  pv: {
    inscripcion: "./assets/images/pv-comunicado-inscripcion.png",
    instructores: "./assets/images/pv-comunicado-instructores.png",
    certificado: "./assets/images/pv-certificado.png",
    backing: "./assets/images/pv-backing.jpg",
    photobooth: "./assets/images/pv-photobooth.png",
    pin: "./assets/images/pv-pin.png",
  },
  gc: {
    logo: "./assets/images/gente-y-cultura.svg",
    ssa: "./assets/images/logo-ssa.svg",
    bienestar: "./assets/images/logo-bienestar.svg",
    salario: "./assets/images/logo-salario-emocional.svg",
    comunicado: "./assets/images/gc-comunicado.jpg",
    ventanas: "./assets/images/gc-brandeo-ventanas.jpg",
    equipo: "./assets/images/gc-brandeo-equipo.jpg",
  },
  ci: {
    c01: "./assets/images/ci-01-modulo-tiempos.png",
    c02: "./assets/images/ci-02-tu-voz.png",
    c03: "./assets/images/ci-03-reconocimientos.png",
    c04: "./assets/images/ci-04-cumpleaneros.png",
    c05: "./assets/images/ci-05-actualizar-imagen.png",
    c06: "./assets/images/ci-06-servicio-nutricional.png",
    c07: "./assets/images/ci-07-jornada-pap.jpg",
  },
  ea: {
    logo: "./assets/images/equipos-agiles.svg",
    isotipo: "./assets/images/isotipo-equipos-agiles.svg",
    video: "./assets/images/ea-edicion-video.jpg",
    com01: "./assets/images/ea-comunicado-01.png",
    com02: "./assets/images/ea-comunicado-02.png",
    kickoff: "./assets/images/ea-invitacion-kickoff.png",
    taller: "./assets/images/ea-invitacion-taller.png",
  },
  oe: {
    keyVisual: "./assets/images/oe-key-visual.png",
    generacionD: "./assets/images/oe-generacion-d.png",
    edificio: "./assets/images/oe-comunicado-edificio.png",
    concurso: "./assets/images/oe-comunicado-concurso.png",
    minutoCivico: "./assets/images/oe-comunicado-minuto-civico.png",
    sesion01: "./assets/images/oe-sesion-01.jpg",
    sesion02: "./assets/images/oe-sesion-02.jpg",
    cob01: "./assets/images/oe-cobertura-01.jpg",
    cob02: "./assets/images/oe-cobertura-02.jpg",
    cob03: "./assets/images/oe-cobertura-03.jpg",
  },
  im: {
    logo: "./assets/images/impulso-logo.svg",
    elementos: "./assets/images/impulso-elementos.svg",
    backing: "./assets/images/impulso-backing.svg",
    comunicado: "./assets/images/im-comunicado.png",
    convocatoria: "./assets/images/im-convocatoria.png",
    lapicero: "./assets/images/im-lapicero.png",
    bolso: "./assets/images/im-bolso.png",
    libreta: "./assets/images/im-libreta.png",
    rollup: "./assets/images/im-rollup.png",
    foto01: "./assets/images/im-foto-01.jpg",
    foto02: "./assets/images/im-foto-02.jpg",
    foto03: "./assets/images/im-foto-03.jpg",
  },
};
